<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>BoxaraXLibrary.GenenicLib.LTS</AssemblyName>

		<PackageId>BoxaraXLibrary.GenenicLib.LTS</PackageId>
		<Version>1.0.1</Version>
		<Authors>JuliHyro Studios Workspace</Authors>
		<Company>JuliHyro Studios Workspace</Company>
		<Product>BoxaraXLibrary.GenenicLib.LTS</Product>
		<Description>Core framework for building shell-based CLI applications with command handling, rich console UI, and fluent API.</Description>
		<PackageTags>shell;cli;command;framework;dotnet;console</PackageTags>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/JuliHyro-Studios/BoxaraXLibrary.GenenicLib.LTS</PackageProjectUrl>
		<RepositoryUrl>https://github.com/JuliHyro-Studios/BoxaraXLibrary.GenenicLib.LTS</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>